language: ruby
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
env:
  - DB=postgresql
gemfile:
  - Gemfile
before_script:
  - psql -c 'create database flashcards_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rspec spec/features/*.rb